<a href="https://colab.research.google.com/github/cgjeong23/Deep-Learning-Models/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.21.5'

In [ ]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0],a1[2])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 3


In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
8


In [ ]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


배열 생성 및 초기화

zeros(): 모든 요소를 0으로 초기화  
ones(): 모든 요소를 1로 초기화  
full(): 모든 요소를 지정한 값으로 초기화  
eye(): 단위행렬 (identitiy matrix) 생성  
--> 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.eye(3)
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

empty(): 초기화 되지 않은 배열 생성  
-초기화가 없어서 배열 생성비용 저렴하고 빠름  
-초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

_like(): 지정된 배열과 shape가 같은 행렬 생성  
-np.zeros_like()
-np.ones_like() 
-np.full_like()
-np.empty_like()

In [ ]:
print(a1)
np.zeros_like(a1)

[1 2 3 4 5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

생성한 값으로 배열생성  
arange(): 정수 범위로 배열 생성  
linspace(): 범위 내에서 균등 간격의 배열 생성  
logspace(): 범위 내에서 균등간격으로 로그 스케일로 배열 생성


In [ ]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

랜덤  
random.random(): 랜덤한 수의 배열 생성 (실수)  
random.randint(): 일정 구간의 랜덤 정수의 배열 생성  


In [ ]:
np.random.random((3,3))

array([[0.69700509, 0.42127106, 0.00818944],
       [0.6281035 , 0.50137929, 0.75176668],
       [0.82600935, 0.59795265, 0.43628488]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[7, 4, 0],
       [1, 7, 0],
       [9, 4, 6]])

그 외 랜덤 generator
  
random.normal(): 정규분포  
random.rand(): 균등분포  
random.randn(): 표준 정규 분포

데이터 타입

In [ ]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

날짜/시간 배열 생성  
y / m /w / d/ h / m/ s / ms

In [ ]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

배열 조회

배열 속성 정보


In [ ]:
def array_info(array):
  print(array)
  print("ndim:", array.ndim)
  print("shape:", array.shape)
  print("dtype:", array.dtype)
  print("itemsize:", array.itemsize)
  print("itemsize:", array.itemsize)
  print("nbytes:", array.nbytes)
  print("strides:", array.strides)

In [ ]:
array_info(a1)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
itemsize: 8
itemsize: 8
nbytes: 40
strides: (8,)


인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])

[1 2 3 4 5]
1


In [ ]:
print(a2)
print(a2[0,0])
print(a2[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3


슬라이싱(Slicing)  
기본값: start=0, stop=ndim, step=1

In [ ]:
print(a1)
print(a1[0:2])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1 3 5]
[5 4 3 2 1]


In [ ]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2,:2])
print(a2[1:,::-1])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


불리언 인덱싱 (Boolean Indexing) & Fancy Indexing

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])


[1 2 3 4 5]
[2 3 5]


In [ ]:
print(a2)
bi = np.random.randint(0,2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True  True False]
 [False  True  True]]
[2 4 5 8 9]


In [ ]:
print(a1)
print([a1[0], a1[2]])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1],[2,0]])
print(a1[ind])

[1 2 3 4 5]
[1, 3]
[1 3]
[[1 2]
 [3 1]]


In [ ]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[5 6]
 [8 9]]


배열 값 삽입/수정/삭제/복사


In [ ]:
print(a1)
b1 = np.insert(a1,0,10)
print(b1)

[1 2 3 4 5]
[10  1  2  3  4  5]


In [ ]:
print(a2)
b2 = np.insert(a2,1,10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


배열 값 수정

In [ ]:
print(a1)
a1[0] = 1
a1[1] = 2
a2[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)

[1 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]


In [ ]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1
print(a2)

[[1 2 3]
 [4 5 6]
 [3 3 3]]
[[1 1 1]
 [4 2 6]
 [3 3 3]]


배열 값 삭제

In [ ]:
print(a1)
b1 = np.delete(a1,1)
print(b1)
print(a1)


[9 0 3 0 0]
[9 3 0 0]
[9 0 3 0 0]


In [ ]:
print(a2)
b2 = np.delete(a2,1,axis=0)
print(b2)
c2 = np.delete(a2,1,axis=1)
print(c2)

[[1 1 1]
 [4 2 6]
 [3 3 3]]
[[1 1 1]
 [3 3 3]]
[[1 1]
 [4 6]
 [3 3]]


배열 복사

In [ ]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 0
print(a2_sub)
print(a2)

[[1 1 1]
 [4 2 6]
 [3 3 3]]
[[1 1]
 [4 2]]
[[1 1]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 6]
 [3 3 3]]


In [ ]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 6]
 [3 3 3]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 6]
 [3 3 3]]


배열 변환

In [ ]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 6]
 [3 3 3]]
[[1 4 3]
 [0 0 3]
 [1 6 3]]


In [ ]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 6]
 [3 3 3]]
[[1 4 3]
 [0 0 3]
 [1 6 3]]


In [ ]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


배열 재구조화

In [ ]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


배열 크기 변경

In [ ]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[2 3 0 3 7]
 [6 9 9 4 5]]
[[2 3]
 [0 3]
 [7 6]
 [9 9]
 [4 5]]


In [ ]:
n2.resize((5,5))
print(n2)

[[2 3 0 3 7]
 [6 9 9 4 5]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


resize로 배열 크기 감소할시, 포함되지 않은 값은 삭제된다

배열추가  
append(): 배열의 끝에 값 추가  
axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
c2 = np.append(a2,b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
c2 = np.append(a2,b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


배열 연결  
concatenate(): 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])

np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])

np.concatenate([a2,a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

vstack(): 수직 스택(vertical stack), 1차원이랑 연결  
hstack(): 수평 스택(horizontal stack), 2차원이랑 연결  
dstack(): 깊이 스택(depth stack), 3차원으로 연결  
stack(): 새로운 차원으로 연결

In [ ]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

배열 분할  
split(): 배열 분할  
vsplit():  
hsplit():  
dsplit():

In [ ]:
a1 = np.arange(0,10)
print(a1)
b1,c1 = np.split(a1,[5])
print(b1,c1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]


배열 연산  
-Numpy의 배열 연산은 벡터화 연산을 사용  
-일반적으로 Numpy의 범용 함수를 통해 구현  
-배열 요소에 대한 반복적인 계산을 효율적으로 수행

브로드캐스팅

In [ ]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1+a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a2+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


percentile

In [ ]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


any()

In [ ]:
a2 = np.array([[False,False,False],
               [False,True,True],
               [False,True,True]])
print(a2)
print(np.any(2))
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


배열 정렬

In [ ]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[8 1 1 1 1 8 7 6 7 6]
[1 1 1 1 6 6 7 7 8 8]
[8 1 1 1 1 8 7 6 7 6]
[1 2 3 4 7 9 6 8 0 5]
[8 1 1 1 1 8 7 6 7 6]
None
[1 1 1 1 6 6 7 7 8 8]


In [ ]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[5 9 7]
 [9 1 5]
 [4 4 7]]
[[4 1 5]
 [5 4 7]
 [9 9 7]]
[[5 7 9]
 [1 5 9]
 [4 4 7]]


부분정렬  
partition(): 배열에서 k개의 작은 값을 반환  


In [ ]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))

[6 9 2 8 7 4 4 5 3 7]
[3 2 4 4 5 6 7 9 8 7]


In [ ]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))

[[2 9 4 9 7]
 [9 9 3 3 2]
 [1 3 2 8 4]
 [3 5 4 8 4]
 [6 7 3 5 2]]
[[2 4 7 9 9]
 [3 2 3 9 9]
 [1 2 3 4 8]
 [3 4 4 5 8]
 [2 3 5 6 7]]
[[1 5 2 3 2]
 [2 3 3 5 2]
 [3 7 3 8 4]
 [6 9 4 8 4]
 [9 9 4 9 7]]
[[2 4 7 9 9]
 [3 2 3 9 9]
 [1 2 3 4 8]
 [3 4 4 5 8]
 [2 3 5 6 7]]


배열 입출력  
np.save() Numpy 배열객체 1개를 파일에 저장  
np.savez() Numpy 배열객체 여러개를 파일에 저장  
np.load() Numpy 배열 저장 파일로부터 객체 로딩  


In [ ]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)
np.save("a",a2)

[[8 6 7 2 9]
 [5 5 6 9 6]
 [5 4 4 2 9]
 [2 3 7 4 3]
 [2 2 9 1 6]]


In [ ]:
!ls

a.npy  sample_data


In [ ]:
b2 = np.random.randint(1,10,size=(5,5))
print(b2)
np.savez("ab", a2, b2)

[[6 3 8 7 7]
 [7 2 1 1 7]
 [8 5 1 9 7]
 [4 5 5 8 8]
 [5 6 9 3 2]]


In [ ]:
!ls

ab.npz	a.npy  sample_data


In [ ]:
npy = np.load("a.npy")
print(npy)

[[8 6 7 2 9]
 [5 5 6 9 6]
 [5 4 4 2 9]
 [2 3 7 4 3]
 [2 2 9 1 6]]


In [ ]:
npz = np.load("ab.npz")
print(npz.files)

['arr_0', 'arr_1']


In [ ]:
print(a2)
np.savetxt("a.csv",a2,delimiter=',')

[[8 6 7 2 9]
 [5 5 6 9 6]
 [5 4 4 2 9]
 [2 3 7 4 3]
 [2 2 9 1 6]]


In [ ]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [ ]:
!cat a.csv

8.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00
5.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,6.000000000000000000e+00
5.000000000000000000e+00,4.000000000000000000e+00,4.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00
2.000000000000000000e+00,3.000000000000000000e+00,7.000000000000000000e+00,4.000000000000000000e+00,3.000000000000000000e+00
2.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00,1.000000000000000000e+00,6.000000000000000000e+00


In [ ]:
csv = np.loadtxt("a.csv", delimiter=',')
print(csv)

[[8. 6. 7. 2. 9.]
 [5. 5. 6. 9. 6.]
 [5. 4. 4. 2. 9.]
 [2. 3. 7. 4. 3.]
 [2. 2. 9. 1. 6.]]


In [ ]:
print(b2)
np.savetxt("b.csv",b2, delimiter=',',fmt='%.2e',header='c1,c2,c3,c4,c5')

[[6 3 8 7 7]
 [7 2 1 1 7]
 [8 5 1 9 7]
 [4 5 5 8 8]
 [5 6 9 3 2]]


In [ ]:
!cat b.csv

# c1,c2,c3,c4,c5
6.00e+00,3.00e+00,8.00e+00,7.00e+00,7.00e+00
7.00e+00,2.00e+00,1.00e+00,1.00e+00,7.00e+00
8.00e+00,5.00e+00,1.00e+00,9.00e+00,7.00e+00
4.00e+00,5.00e+00,5.00e+00,8.00e+00,8.00e+00
5.00e+00,6.00e+00,9.00e+00,3.00e+00,2.00e+00


In [ ]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[6. 3. 8. 7. 7.]
 [7. 2. 1. 1. 7.]
 [8. 5. 1. 9. 7.]
 [4. 5. 5. 8. 8.]
 [5. 6. 9. 3. 2.]]
